### PR TITLE
Allow for reusing previous authentication after a device reboot

### PR DESCRIPTION
**Pull request by imbradbrown**
Relates to #19 

Steps:
1. Login with a valid account
1. Once the Authorized Granted appears reboot the device
1. Launch the app
    * The refresh token (if applicable) and user info buttons should work without NPE

### CODE REVIEW

**Comment by bdemers** [comment]
Thanks @imbradbrown!!
Can you sign our CLA?
https://developer.okta.com/cla/

**Comment by imbradbrown** [comment]
Submitted just now @bdemers Thanks for looking at the PR.

**Comment by smokienko** [comment]
@imbradbrown thanks for pull request it resolves the issue with reusing the previous Authentication but only partially. 
The core issue lies in using `JSONObject.hashCode()` which does not generate the same hash codes for equal objects but used as an identifier of OktaConfig.
I am going to push a fix for this within the next few days than we need to test your solution against the new version so we can accept it.

**Comment by imbradbrown** [comment]
@smokienko Found the same which seems to have been fixed as part of https://github.com/okta/okta-sdk-appauth-android/pull/24.

**Comment by smokienko** [comment]
@imbradbrown missed that pull request, sorry, other than that looks fine for me

**Comment by bdemers** [comment]
Merged manually

Side note, I initially tried to revolve the conflicts through the GitHub web UI, that didn't work...

Thanks again @imbradbrown!

**Pull request closed without merging**
